-- Documentation: <https://github.com/nvim-treesitter/nvim-treesitter>
---@module 'lazy'
---@type LazyPluginSpec
local M = {
  "nvim-treesitter/nvim-treesitter",
  dependencies = { "nvim-treesitter/nvim-treesitter-textobjects" },
  build = ":TSUpdate",
  config = function(plugin, opts)
    require("nvim-treesitter.configs").setup(opts)
  end,
  opts = {
    auto_install = false,
    ignore_install = {},
    ensure_installed = {
      -- The following must ALWAYS be installed...
      "c",
      "lua",
      "vim",
      "vimdoc",
      "query",
      "markdown",
      "markdown_inline",
      -- ...

      "asm",
      "bash",
      "commonlisp",
      "cpp",
      "css",
      "elixir",
      "elm",
      "fish",
      "fortran",
      "go",
      "goctl",
      "gomod",
      "gotmpl",
      "gowork",
      "groovy",
      "haskell",
      "html",
      "java",
      "javascript",
      "julia",
      "kotlin",
      "luadoc",
      "meson",
      "nix",
      "norg",
      "ocaml",
      "perl",
      "purescript",
      "python",
      "requirements",
      "rust",
      "scala",
      "scss",
      "sql",
      "svelte",
      "typescript",
      "typst",
      "zig",

      "diff",
      "disassembly",
      "dockerfile",
      "editorconfig",
      "gitattributes",
      "gitcommit",
      "git_config",
      "gitignore",
      "git_rebase",
      "gpg",
      "http",
      "just",
      "llvm",
      "make",
      "nginx",
      "objdump",
      "passwd",
      "printf",
      "properties",
      "readline",
      "regex",
      "ssh_config",
      "udev",
      "zathurarc",

      "csv",
      "ini",
      "json",
      "json5",
      "jsonc",
      "toml",
      "xml",
      "yaml",

      "comment",
      "desktop",
      "hyprlang",
    },
    highlight = { enable = true },
    indent = { enable = true },
    -- TODO: Configure...
    -- incremental_selection = { },
    -- textobjects = { },
  },
}

return { M }
